# Generated by Django 5.1.2 on 2024-11-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airline', to='flights.flights')),
            ],
        ),
    ]
