# Generated by Django 5.1.2 on 2024-11-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locator', models.CharField(max_length=10, unique=True)),
                ('e_ticket_number', models.CharField(max_length=12, unique=True)),
                ('num_passengers', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights.flights')),
            ],
        ),
    ]
